stages:
  - test

.COMMON_BEFORE_SCRIPT: &COMMON_BEFORE_SCRIPT
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
    - mix deps.compile
    - apt-get update

.COMMON_CONFIGS: &COMMON_CONFIGS
  stage: test
  image: elixir:1.8

test:
  <<: *COMMON_CONFIGS
  <<: *COMMON_BEFORE_SCRIPT
  script:
    - mix test
