version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./run.sh
    volumes:
      - .:/app
    environment:
      PORT: 4000
      HOSTNAME: localhost
    ports:
      - "4000:4000"
    depends_on:
      - redis
